apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: voting-app
spec:
  template:
    spec:
      containers:
        - image: docker.io/nachogmz/voting-app:v2
          ports:
            - containerPort: 8001
  
